disable blink.cmp remaps when telescope prompt is open
Saghen/blink.cmp pull request #104
Opened 2024-10-12 10:06 UTC by Jezda1337

close #102

2024-10-12 13:39 UTC, pappasam commented
Confirmed that this resolves the issue for me!

2024-10-12 13:52 UTC, sjava commented
Hope to add ignore_buffer_type to the configuration options

2024-10-12 18:18 UTC, simifalaye commented
Could be a good idea to also make the excluded file types be configurable by the user?

2024-10-12 18:25 UTC, Rentib commented
@Jezda1337 won't it be better to make a map: filetype -> bool instead of iterating over excluded filetypes?

2024-10-12 18:44 UTC, Jezda1337 commented
Thank you for the suggestions. I have implemented them as you suggested. Cheers!

2024-10-12 19:18 UTC, scottmckendry commented
My only qualm with this is that the config option gives the impression the plugin will be disabled for the file types inside the table. This might cause some confusion.

Does it make more sense to turn off blink entirely than just the keymaps?

2024-10-12 20:24 UTC, Saghen commented
The triggers should also be disabled and the table should be array-like instead of a key = true

2024-10-12 20:54 UTC, Saghen commented
Seems like utils.is_special_buffer() would handle this case without a dedicated blocklist fyi

2024-10-12 21:39 UTC, scottmckendry commented
This would have the added benefit of closing #52. Probably out of scope for this PR, but we should also think about extending this functionality with user commands like `:blink status`, `:blink toggle`, `:blink enable` and `:blink disable`.

Exposing these via lua APIs would also be useful for custom user functionality for the plugin too.

2024-10-13 09:24 UTC, Jezda1337 commented
@scottmckendry @Saghen I have updated PR based on Scott's example. Since `utils.is_sepcial_buffer()` covers all cases I think we don't need an additional config list for the same purpose, wdyt?

2024-10-13 17:19 UTC, scottmckendry commented
@Jezda1337 great stuff! That approach made more sense when used with the `exclude_filetypes` approach. However, now that I've thought about it some more, it may make more sense to use `is_special_buffer()` directly inside the trigger logic.

This would remove the need to set a global variable for buffer-specific logic as well as the extra autocmd in `init.lua`.

2024-10-13 17:26 UTC, scottmckendry requested changes

2024-10-13 17:26 UTC, scottmckendry commented on lua/blink/cmp/keymap.lua
> +      if not vim.g.blinkcmp_enabled then return end
```suggestion
      if utils.is_special_buffer() then return end
```

2024-10-13 17:26 UTC, scottmckendry commented on lua/blink/cmp/init.lua
> +
This can be removed in favour of `utils.is_special_buffer()` in the suggested change in `keymap.lua`

2024-10-13 17:26 UTC, scottmckendry commented on lua/blink/cmp/trigger/completion.lua
> +
Should be safe to remove this outright. There is already a check for `is_special_buffer()` in this autocmd.

2024-10-13 17:26 UTC, scottmckendry commented on lua/blink/cmp/trigger/signature.lua
> +
Same here ;)

2024-10-13 17:37 UTC, Jezda1337 commented
@scottmckendry Hey, thanks for the suggestions. I have applied them all. Please feel free to check and ask for additional changes if you need them. I have tested and everything works as before. Cheers!

2024-10-13 17:41 UTC, scottmckendry approved these changes

2024-10-13 17:42 UTC, merged

2024-10-13 17:43 UTC, scottmckendry commented
@Jezda1337 thanks for your efforts! I've merged with a couple of minor changes.