fix(fallback): make fallback work with buffer-local mappings
Saghen/blink.cmp pull request #483
Opened 2024-12-09 23:12 UTC by folke

Fixes #482

2024-12-10 16:55 UTC, Saghen requested changes

2024-12-10 16:55 UTC, Saghen commented on lua/blink/cmp/keymap/apply.lua
> +    local fallback = require('blink.cmp.keymap.fallback').wrap('i', key)
Doing this ahead of time introduces a timing issue, where keymaps created after blink initializes its keymaps will be ignored

2024-12-10 16:57 UTC, folke commented on lua/blink/cmp/keymap/apply.lua
> +    local fallback = require('blink.cmp.keymap.fallback').wrap('i', key)
IF they are created after blink initiaizes then they will override the blink keymaps. When the blink keymaps are re-created afterwards, the fallback will also be correct again.

2024-12-10 16:58 UTC, folke commented on lua/blink/cmp/keymap/apply.lua
> +    local fallback = require('blink.cmp.keymap.fallback').wrap('i', key)
The only correct way/time to check for a fallbacks is right before creating the blink keymap.
Only one keymap can exist for a given mode/key.

2024-12-10 16:59 UTC, Saghen commented on lua/blink/cmp/keymap/apply.lua
> +    local fallback = require('blink.cmp.keymap.fallback').wrap('i', key)
p.s. the existing code that loops over all insert mode keybinds takes 0.0002ms on my system so it shouldn't be an issue

2024-12-10 17:00 UTC, folke commented on lua/blink/cmp/keymap/apply.lua
> +    local fallback = require('blink.cmp.keymap.fallback').wrap('i', key)
right, will give issues for global keymaps

2024-12-10 17:02 UTC, Saghen commented on lua/blink/cmp/keymap/apply.lua
> +    local fallback = require('blink.cmp.keymap.fallback').wrap('i', key)
We should grab the buffer local keymap before applying but then still loop over global keymaps if the buffer local mapping was undefined

2024-12-10 19:24 UTC, folke commented on lua/blink/cmp/keymap/apply.lua
> +    local fallback = require('blink.cmp.keymap.fallback').wrap('i', key)
Updated. The buffer-local mapping is saved on create and global mappings are checked when executing the fallback.

2024-12-10 19:34 UTC, merged

2024-12-10 19:34 UTC, Saghen commented
Thanks!

2024-12-10 20:04 UTC, folke commented
ty!

2024-12-11 14:36 UTC, vdegenne commented
@folke I thought this PR would fix https://github.com/LazyVim/LazyVim/issues/4958#issuecomment-2520695186 but it didn't

2024-12-12 13:17 UTC, Parsifa1 commented
```lua
create_undo_point = false,
```
this could fix the error, we should find out what happened.