fix!: autocompletion window components alignment
Saghen/blink.cmp pull request #51
Opened 2024-10-09 02:21 UTC by lopi-py

Before
![image](https://github.com/user-attachments/assets/371c2cba-5575-4ca5-9d8f-0ced74a7c7c7)
After
![image](https://github.com/user-attachments/assets/d2962f64-370f-45b2-afb6-2c43605b2e73)

I have a custom `windows.autocomplete.draw` function:
```lua
draw = function(ctx)
  return {
    {
      ctx.item.label,
      ctx.kind == "Snippet" and "~" or nil,
      fill = true,
      hl_group = ctx.deprecated and "BlinkCmpLabelDeprecated" or "BlinkCmpLabel",
    },
    " ",
    { ctx.kind, hl_group = "BlinkCmpKind" .. ctx.kind },
  }
end
```
## Notes
* I've removed `windows.autocomplete.min_width` and `windows.autocomplete.max_width` since it's way easier to maintain the alignment without those, but in compensation, `max_width` component option was added:
```lua
draw = function(ctx)
  return {
    {
      ctx.item.label,
      ctx.kind == "Snippet" and "~" or nil,
      fill = true,
      max_width = 5,
      hl_group = ctx.deprecated and "BlinkCmpLabelDeprecated" or "BlinkCmpLabel",
    },
    " ",
    { ctx.kind, hl_group = "BlinkCmpKind" .. ctx.kind },
  }
end
```
![image](https://github.com/user-attachments/assets/29ca9f1b-c900-4feb-9d84-309db99ff47e)
Also it feels weird to have unnecessary blank spacing with the `windows.autocomplete.min_width` option

* This PR allows for multiple `fill` components
* Added padding for both left and right sides of the display item

2024-10-09 19:17 UTC, Saghen requested changes
Great work! The multiple fills and max_width make a few layout ideas I had much easier. One small change, a rebase and I'll merge

2024-10-09 19:17 UTC, Saghen commented on lua/blink/cmp/windows/lib/render.lua
> +end
This prevents people from creating highlights from edge to edge so I think I'd prefer we leave it as-is

2024-10-10 02:24 UTC, Saghen commented on lua/blink/cmp/windows/lib/render.lua
> +    return text:sub(1, max_width) .. '…'
should this be `max_width - 1`?

2024-10-10 02:37 UTC, lopi-py commented on lua/blink/cmp/windows/lib/render.lua
> +    return text:sub(1, max_width) .. '…'
I thought that if I set max_width to say 5, I only want to see 5 characters maximum, regardless the ellipsis character (...). With `max_width - 1` I would only see 4

2024-10-10 02:49 UTC, lopi-py commented on lua/blink/cmp/windows/lib/render.lua
> +    return text:sub(1, max_width) .. '…'
Also, should I use `vim.fn.strcharpart` instead of `string.sub` right? the former handles +2 cells characters like the `nvim_strwidth` function, my only concern would be performance because of the vim bridge `lua -> vim -> lua` but we probably will never hit a performance issue right? here are some benchmarks on my computer:
- string.sub on 200 items: ~0.1ms
- vim.fn.strcharpart on 200 items: ~0.5ms

But it's not so common to truncate all the completion items I think so we probably will never hit a performance issue

2024-10-10 03:04 UTC, Saghen commented on lua/blink/cmp/windows/lib/render.lua
> +    return text:sub(1, max_width) .. '…'
Yeah shouldnt be an issue, it's good with me

2024-10-10 05:06 UTC, lopi-py commented
I had fun with git 🥹.
It should be ready now @Saghen, also would you accept a PR to add snippets indicators and the draw function I made?
![image](https://github.com/user-attachments/assets/1d2d4a06-bde1-4836-90e4-ce71f287d5fd)

2024-10-10 05:14 UTC, Saghen commented
Yep I would, should they be at the beginning instead?

2024-10-10 05:21 UTC, lopi-py commented
It feels like its missaligned with the other items, actually, the snippet indicator is taken from nvim-cmp

2024-10-10 22:43 UTC, merged

2024-10-10 22:43 UTC, Saghen commented
Thank you!